{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mtgs.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
{{ include "mtgs.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $h := .Values.ingress.hosts }}
    - host: {{ $h | quote }}
      http:
        paths:
          - path: {{ default "/" $ingressPath | quote }}
            backend:
              serviceName: {{ $fullName }}-api
              servicePort: api
  {{- end }}
{{- end }}
