apiVersion: v1
kind: Service
metadata:
  name: {{ include "mtgs.fullname" . }}-api
  labels:
{{ include "mtgs.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "mtgs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
